name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
  Build:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: gradle build
        run: ./gradlew build -x test

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: gradle test
        run: ./gradlew test

