name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Test
      run: ./gradlew test

    - name: Build bootstrap compiler
      run: ./gradlew installDist

    - name: Test Stage 1
      run: python3 test.py
      working-directory: ./test

    - name: Archive Test Results
      if: always() # Even on failures
      uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: hadesboot/build/reports/tests/test
