name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: gradle test
      run: ./gradlew test
    - name: gradle build
      run: ./gradlew build -x test

    - name: Archive Test Results
      if: always() # Even on failures
      uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: hadesboot/build/reports/tests/test

    - name: Create tar
      run: ./gradlew distTar
