---
name: Release Latest

on:
  push:
    branches: [ master ]

jobs:
  latest-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradle build
        run: ./gradlew build

      - name: Create tar
        run: ./build_all_distributions.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            hadesboot/build/distributions/hades.tar
            hadesboot/build/distributions/hades-linux-x86_64.tar
            hadesboot/build/distributions/hades-macos-x86_64.tar
            hadesboot/build/distributions/hades-windows-x86_64.tar
