name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          $env:PATH = $env:PATH + ";C:\msys64\usr\bin"
          $env:JAVA_HOME = $JAVA_HOME_11_X64
          echo $env:PATH
          echo $env:JAVA_HOME
      - name: Install gcc
        run: pacman --noconfirm -Sy gcc

      - name: Build with Gradle
        run: .\gradlew build -x test
      - name: test
        run: .\gradlew test
