name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install gcc
        run: |
          ${{ env.MSYSBIN }}\pacman --noconfirm -Sy gcc

      - name: Build with Gradle
        run: |
          echo $env:JAVA_HOME
          ${{env.MSYSBIN}}\bash -c "JAVA_HOME=`$JAVA_HOME_11_X64 ./gradlew build -x test"
      - name: test
        run: |
          ${{env.MSYSBIN}}\bash -c "JAVA_HOME=`$JAVA_HOME_11_X64 ./gradlew test"

        env:
          CC: ${{ env.MSYSBIN }}\gcc
