name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build with Gradle
        run: |
          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
          .\gradlew build

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: hadesboot/build/reports/tests/test
