name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          PATH = $env:PATH + ";C:\msys64\usr\bin"
          JAVA_HOME = $JAVA_HOME_11_X64
          echo "PATH=$env:PATH" >> $GITHUB_ENV
          echo "JAVA_HOME=$env:JAVA_HOME" >> $GITHUB_ENV
      - name: Install gcc
        run: pacman --noconfirm -Sy gcc

      - name: Build with Gradle
        run: .\gradlew build -x test
      - name: test
        run: .\gradlew test
