name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo "PPATH=`"C:\msys64\usr\bin;$env:PATH`"" >> $GITHUB_ENV
          echo "JAVA_HOME=$env:JAVA_HOME_11_X64" >> $GITHUB_ENV
      - name: Show environment
        run: |
          echo $env:JAVA_HOME
          echo $env:PPATH
      - name: Install gcc
        run: PATH=$PPATH pacman --noconfirm -Sy gcc

      - name: Build with Gradle
        run: .\gradlew build -x test
      - name: test
        run: .\gradlew test
