name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\
      CC: C:\msys64\usr\bin\gcc

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install gcc
        run: C:\msys64\usr\bin\pacman --noconfirm -Sy gcc
      - name: Print Java Home
        run: echo $JAVA_HOME_11
      - name: Build with Gradle
        run: C:\msys64\usr\bin\bash -c "JAVA_HOME=$$JAVA_HOME_11_X64 ./gradlew build -x test"

      - name: test
        run: .\gradlew test
