name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install gcc
      - run: ${{ env.MSYSBIN }}/pacman -Sy --noconfirm gcc

      - name: Build with Gradle
        run: |
          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
          $env:CC = ${{ env.MSYSBIN }}/gcc
          .\gradlew build
