name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MSYSBIN: C:\msys64\usr\bin\
      CC: C:\msys64\usr\bin\gcc

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install gcc
        run: /c/msys64/usr/bin/pacman --noconfirm -Sy gcc
        shell: C:\msys64\usr\bin\bash
      - name: Print Java Home
        run: echo $JAVA_HOME_11_X64
        shell: C:\msys64\usr\bin\bash
      - name: Build with Gradle
        run: JAVA_HOME=$JAVA_HOME_11_X64 ./gradlew build -x test"
        shell: C:\msys64\usr\bin\bash
      - name: test
        run: JAVA_HOME=$JAVA_HOME_11_X64 .\gradlew test
        shell: C:\msys64\usr\bin\bash
